owner: ctrl-i
repo: uptime
user-agent: uptime-boffin

sites:
  - name: Boffin
    url: $BOFFINURL
    icon: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/boff.in.png
  - name: Mail Boffin
    url: $MAILURL
    icon: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/mailcow.png
  - name: Email
    url: $EMAILURL
    icon: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/mailboffin.svg
  - name: Server IPv4
    check: "tcp-ping"
    url: $IPV4
    port: 80
    icon: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/ipv4.svg
  - name: Server IPv6
    check: "tcp-ping"
    url: $IPV6
    port: 80
    icon: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/ipv6.svg
    
status-website:
  cname: uptime.boff.in
  logoUrl: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/uptime.svg
  name: Uptime Boffin
  favicon: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/uptime.png
  faviconSvg: https://raw.githubusercontent.com/ctrl-i/uptime/master/assets/uptime.svg
  metaTags:
    - name: "robots"
      content: "noindex"

robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

skipDescriptionUpdate: true
skipTopicsUpdate: true

